# Catppuccin Mocha -- generated by theme-switcher.
# Sourced by ~/.zshrc. Rewritten per theme so `ls` and friends agree with the
# desktop instead of keeping whatever dircolors last wrote.

export LS_COLORS='di=38;2;137;180;250:ln=38;2;148;226;213:ex=38;2;166;227;161:pi=38;2;249;226;175:so=38;2;203;166;247:bd=38;2;249;226;175:cd=38;2;249;226;175:or=38;2;243;139;168:mi=38;2;243;139;168:ow=38;2;166;173;200:tw=38;2;203;166;247:st=38;2;203;166;247:su=38;2;203;166;247:sg=38;2;203;166;247:ca=38;2;203;166;247:tu=38;2;203;166;247:'
