# Gruvbox Dark -- generated by theme-switcher.
# oh-my-zsh prompt theme. ~/.zshrc points ZSH_THEME at
# ~/.oh-my-zsh/custom/themes/theme-gruvbox.zsh-theme, which is a symlink to this
# file, because oh-my-zsh appends ".zsh-theme" itself and searches only its own
# theme directories -- it cannot be given a path.

# Plain assignments, deliberately not 'local': this file is sourced at the top
# level, outside any function, where local is not a function scope.
#
# The values are real ANSI escapes, not hex strings. A prompt cannot use
# "#rrggbb", and dropping one inside %{%...%} fails silently rather than
# loudly: %{%...%} marks its contents zero-width, so the hex digits are made
# invisible and the colour simply never appears.
c_fg=$'\e[38;2;235;219;178m'
c_accent=$'\e[38;2;235;219;178m'
c_blue=$'\e[38;2;254;128;25m'
c_red=$'\e[38;2;213;196;161m'
c_green=$'\e[38;2;189;174;147m'
c_yellow=$'\e[38;2;250;189;47m'
c_dim=$'\e[38;2;146;131;116m'
c_off=$'\e[0m'

PROMPT='%{$c_accent%}╭─%{$c_dim%} [%{$c_fg%}%n%{$c_dim%}] [%{$c_blue%}%~%{$c_dim%}]%{$c_accent%}'
PROMPT+='%(!.#%{$c_green%}❯ .%{$c_accent%}❯ )'
RPROMPT='%{$c_dim%}[%{$c_yellow%}%D{%H:%M}%{$c_dim%}]%{$c_accent%}╯%{$c_off%}'
ZLE_RPROMPT_INDENT='  '

setopt promptsubst

_prompt_git() {
  if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
    local branch dirty
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
    dirty=$(git status --porcelain 2>/dev/null | head -1)
    printf ' %sgit:%s%s%s' "$c_dim" "$c_blue" "$branch" "$c_dim"
    [[ -n "$dirty" ]] && printf '%s●%s' "$c_red" "$c_dim"
    printf ' %s' "$c_off"
  fi
}

_prompt_status() {
  local code=$?
  if (( code != 0 )); then
    RPROMPT="${c_red}${code}${c_dim} %D{%H:%M}${c_accent}╯${c_off}"
  else
    RPROMPT="${c_dim}%D{%H:%M}${c_accent}╯${c_off}"
  fi
  return $code
}

# add-zsh-hook comes from oh-my-zsh. Guard it so the file can also be sourced
# directly (zsh -f, a test harness) without three "command not found" errors.
if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook precmd _prompt_git
  add-zsh-hook precmd _prompt_status
  add-zsh-hook preexec _prompt_status
fi
