-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "21")

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.95,
        blur = {
            enabled = false,
            passes = 1,
            size = 3,
        },
        inactive_opacity = 0.85,
        rounding = 5,
        shadow = {
            color = "0xee1a1a1a",
            enabled = true,
            range = 4,
        },
    },
    general = {
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(c0bfbcff)"},
                angle = 45,
            },
            inactive_border = "0xffffffff",
        },
        gaps_out = 5,
        layout = "dwindle",
    },
})
