-- Colourscheme wiring for the system theme switcher.
--
-- ~/.config/nvim/lua/config/theme.lua is generated by `theme-switcher` and
-- holds only the name to load. Keeping the choice in a data file rather than in
-- this spec means switching themes does not touch this file, and this file
-- never has to be edited by the switcher.
--
-- Previously this was lua/plugins/gruvbox.lua with `colorscheme = "gruvbox"`
-- hardcoded in LazyVim's opts. The gruvbox options below are unchanged.
--
-- Three palettes map onto three schemes:
--
--   gruvbox            -> gruvbox (ellisonleao/gruvbox.nvim)
--   catppuccin-mocha   -> catppuccin (catppuccin/nvim), flavour mocha
--   monochrome         -> colors/monochrome.lua, written by the switcher.
--                          There is no upstream greyscale scheme for Neovim, so
--                          one is generated from the palette instead of
--                          deriving from an existing scheme, which would leave
--                          that scheme's hues showing through.
--
-- The `name =` fields are explicit on purpose. LazyVim looks the colorscheme up
-- by plugin name, and lazy.nvim derives a default name from the repo URL, which
-- for gruvbox.nvim is ambiguous. Stating the name removes the guesswork.

local theme = require("config.theme")

-- catppuccin reads this when it is loaded, which has to happen before
-- `:colorscheme catppuccin` runs. Setting it here rather than in opts is
-- deliberate: opts are applied by lazy.nvim at load time, and LazyVim applies
-- the colorscheme in the same pass, so relying on opts alone is a race.
if theme.colorscheme == "catppuccin" then
	vim.g.catppuccin_flavour = theme.flavour
end

return {
	{
		"ellisonleao/gruvbox.nvim",
		name = "gruvbox",
		-- NOTE: `setup()` must run before the colorscheme is applied, so this
		-- plugin is loaded eagerly (lazy = false) instead of being pulled in by
		-- `:colorscheme`.
		lazy = false,
		priority = 1000,
		opts = {
			terminal_colors = true,
			undercurl = true,
			underline = true,
			bold = true,
			italic = {
				strings = true,
				emphasis = true,
				comments = true,
				operators = false,
				folds = true,
			},
			strikethrough = true,
			contrast = "", -- "" | "soft" | "hard"
			dim_inactive = false,
			transparent_mode = false,
			palette_overrides = {},
			overrides = {},
		},
	},

	{
		"catppuccin/nvim",
		name = "catppuccin",
		lazy = false,
		priority = 1000,
		opts = {
			flavour = theme.flavour,
			transparent_background = false,
			term_colors = true,
			styles = {
				comments = { "italic" },
				conditionals = { "italic" },
				loops = {},
			},
			integrations = {
				nvimtree = true,
				gitsigns = true,
				mini = true,
				which_key = false,
			},
		},
	},

	-- Make LazyVim load whichever scheme the system theme asks for.
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = theme.colorscheme,
		},
	},
}